# Generated by Django 4.2.13 on 2024-06-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationid', models.IntegerField()),
                ('applicant', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=50)),
                ('cnn', models.IntegerField()),
                ('location_description', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('blocklot', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=20)),
                ('lot', models.CharField(max_length=20)),
                ('permit', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('food_items', models.TextField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('schedule', models.URLField()),
                ('dayshours', models.CharField(blank=True, max_length=255, null=True)),
                ('nois_sent', models.DateTimeField(blank=True, null=True)),
                ('approved', models.DateTimeField()),
                ('received', models.DateTimeField()),
                ('prior_permit', models.BooleanField()),
                ('expiration_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('fire_prevention_districts', models.IntegerField()),
                ('police_districts', models.IntegerField()),
                ('supervisor_districts', models.IntegerField()),
                ('zip_codes', models.IntegerField()),
                ('neighborhoods_old', models.CharField(max_length=255)),
            ],
        ),
    ]
